---
title: "Atlas de Desarrollo Humano Cantonal"
subtitle: <a href="https://www.undp.org/es/costa-rica/publicaciones/atlas-de-desarrollo-humano-cantonal-2024">Fuente - PNUD</a>
format: 
  dashboard:
    orientation: columns
    theme: yeti
    nav-buttons: 
      - reddit
      - twitter
      - linkedin
      - icon: github
        href: https://github.com/gf0604-procesamientodatosgeograficos/2025-i-atlas-desarrollo-humano
---

```{r}
#| label: cargar-bibliotecas

library(tidyverse)
library(sf)
library(terra)
library(plotly)
library(DT)
library(readxl)
library(tmap)
library(bslib)
library(bsicons)
```

```{r}
#| label: cargar-datos

# Cargar datos de cantones
cantones <- st_read("cantones-simplificados.gpkg", quiet = TRUE)

# Cargar datos del Índice de Desarrollo Humano (IDH)
idh <- read_excel("indice_de_desarrollo_humano.xlsx", sheet = "IDH")

# Cambiar nombres de columnas
idh <-
  idh |>
  rename(
    idh_2010 = `2010`, idh_2011 = `2011`, idh_2012 = `2012`, idh_2013 = `2013`,
    idh_2014 = `2014`, idh_2015 = `2015`, idh_2016 = `2016`, idh_2017 = `2017`,
    idh_2018 = `2018`, idh_2019 = `2019`, idh_2020 = `2020`, idh_2021 = `2021`,
    idh_2022 = `2022`
  )

# Crear la columna CÓDIGO_CANTÓN (mismo nombre que tiene en cantones)
idh <- 
  idh |>
  mutate(
    `CÓDIGO_CANTÓN` = substr(Cantón, 1, 3) |> # toma los 3 primeros caracteres
                      as.integer()            # los convierte a entero
  )

# Unión de cantones e índices
cantones_indices <-
  cantones |>
  left_join(
    idh,
    by = "CÓDIGO_CANTÓN"
  )

# DATOS CLAVE

idh_promedio <- mean(cantones_indices$idh_2022, na.rm = TRUE)
canton_mayor_idh <- cantones_indices |> slice_max(idh_2022, n = 1)
canton_menor_idh <- cantones_indices |> slice_min(idh_2022, n = 1)

# Densidad de población
densidad_poblacion <- rast("densidad-poblacion.tif")
```

## Column {width=50%}

### Row {height=30%}

```{r}
#| label: valueboxes

layout_column_wrap(
  width         = 1/3,          # 3 columnas
  heights_equal = "row",        # misma altura por fila
  gap           = "0.75rem",    # separación
  value_box(
    title     = "Promedio nacional IDH",
    value     = scales::number(idh_promedio, .001),
    showcase = bs_icon("globe-americas"),  # https://icons.getbootstrap.com/
    theme     = "primary"  # https://quarto.org/docs/reference/formats/dashboard.html
  ),
  value_box(
    title     = paste("Mayor IDH:", canton_mayor_idh$CANTÓN),
    value     = scales::number(canton_mayor_idh$idh_2022, .001),
    showcase  = bs_icon("arrow-up-circle"),
    theme     = "success"
  ),
  value_box(
    title     = paste("Menor IDH:", canton_menor_idh$CANTÓN),
    value     = scales::number(canton_menor_idh$idh_2022, .001),
    showcase  = bs_icon("arrow-down-circle"),
    theme     = "danger"
  )
)
```

### Row {height=70%}

```{r}
#| label: mapa-idh

# Mapa interactivo
tmap_mode("view")

# Definir y configurar el mapa
mapa <-
  tm_view(set_view = c(lon = -84.2, lat = 9.6, zoom = 7)) +
  tm_basemap(c("Esri.WorldGrayCanvas", "OpenStreetMap", "Esri.WorldImagery")) +
  # Densidad de población
  tm_shape(densidad_poblacion, name = "Densidad de ´población") +
  tm_raster(
    style = "quantile",
    palette = c("yellow", "orange", "red"), 
    title = "Densidad de población"
  ) +
  tm_shape(cantones_indices, name = "Cantones") +
    tm_fill(
      fill = "idh_2022",
      fill.scale = tm_scale_intervals(
      style  = "quantile",
      values = "Blues"
    ),
    fill.legend = tm_legend(title = "IDH"),
    id = "CANTÓN",
    popup.vars  = c(
      "Cantón" = "CANTÓN",
      "IDH" = "idh_2022"
    )
  ) +
  tm_borders(col = "black", lwd = 0.5) +
  tm_scale_bar(position = c("left", "bottom"))

# Mostrar el mapa
mapa
```

## Column {width=50%}

### Row {.tabset}

```{r}
#| label: grafico-cantones-mayor-idh
#| title: "Cantones con mayor IDH"

# Definir el gráfico ggplot2
grafico <-
  cantones_indices |>
  arrange(-idh_2022) |>
  slice_head(n = 15) |>
  ggplot(aes(x = reorder(CANTÓN, -idh_2022), y = idh_2022)) +
  geom_col(
    aes(
      text = paste0(
        "Cantón: ", CANTÓN, "\n",
        "IDH: ", round(idh_2022, 3)
      )
    ),
    fill = "#1f77b4"
  ) +
  xlab("Cantón") +
  ylab("IDH") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # etiquetas a 45°

# Mostrar el gráfico plotly
ggplotly(grafico, tooltip = "text") |> 
  config(locale = 'es')
```

```{r}
#| label: grafico-cantones-menor-idh
#| title: "Cantones con menor IDH"

# Definir el gráfico ggplot2
grafico <-
  cantones_indices |>
  arrange(-idh_2022) |>
  slice_tail(n = 15) |>
  ggplot(aes(x = reorder(CANTÓN, idh_2022), y = idh_2022)) +
  geom_col(
    aes(
      text = paste0(
        "Cantón: ", CANTÓN, "\n",
        "IDH: ", round(idh_2022, 3)
      )
    ),
    fill = "#6BAED6"
  ) +
  xlab("Cantón") +
  ylab("IDH") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # etiquetas a 45°

# Mostrar el gráfico plotly
ggplotly(grafico, tooltip = "text") |> 
  config(locale = 'es')
```

### Row

```{r}
#| label: tabla-idh-cantones
#| title: "IDH de todos los cantones"

# Definir tabla
tabla <-
  cantones_indices |>
  st_drop_geometry() |>
  dplyr::select(PROVINCIA, CANTÓN, idh_2022) |>
  mutate(idh_2022 = round(idh_2022, 3)) |>
  arrange(desc(idh_2022)) |>                 
  datatable(
    rownames = FALSE,
    colnames = c("Provincia", "Cantón", "IDH"),
    options = list(                 
      dom = 'ft',
      pageLength = 8,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )    
  )

# Mostrar tabla
tabla
```


